services:
  dbss:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    
  frontend:
    build:
      context: ../tija_pms_frontend
      dockerfile: Dockerfile
    volumes:
      - ../tija_pms_frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - web

volumes:
  postgres_data:
