
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ../tija_pms_frontend # Path to the frontend directory
      dockerfile: Dockerfile # If you named it frontend.Dockerfile, change this to frontend.Dockerfile
    volumes:
      - ../tija_pms_frontend:/app  # Mounts frontend code for hot reloading during development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development  # Adjust as needed
    depends_on:
      - web  # Ensures the backend is up before starting the frontend
volumes:
  postgres_data:
