# Generated by Django 5.1 on 2024-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='jurisdiction_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
