# Generated by Django 5.1.1 on 2024-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
    ]


# Generated by Django 5.1.1 on 2024-11-13 07:11

from django.db import migrations


# Generated by Django 5.1.1 on 2024-11-13 06:42

from django.db import migrations


def create_default_unit_types(apps, schema_editor):
    unit_type = apps.get_model('core', 'UnitType')

    default_statuses = [
        {
            'name': 'Branch',
            'description' : "Usually located across various regions or locations"
         },
        {
            'name': 'Department',
            'description': 'division that focuses on specific functions or areas of expertise, such as finance, human resources, or marketing, contributing to the broader goals of the organizationc '
        },
        {
            'name': 'Team',
            'description' : 'A group of individuals working collaboratively within a department or branch, often on specific projects or tasks, to achieve common objectives and support organizational goals'
        }
    ]

    for status in default_statuses:
        unit_type.objects.get_or_create(**status)

def create_default_entity_types(apps, schema_editor):
    entity_type = apps.get_model('core', 'EntityType')

    default_statuses = [
        {
            'name': 'Holding Company',
            'description' : "An entity consisting of more than one sub-entity"
         },
        {
            'name': 'Single Entity Company',
            'description': 'An entity that is a singular entity'
        },
      
    ]

    for status in default_statuses:
        entity_type.objects.get_or_create(**status)


def create_default_admin_types(apps,schema_editor):
    admin_type = apps.get_model('core','AdminType')
    default_task_types = [
        {
            'name': 'SUP',
            'description' : "Superuser. Has access to the entire system"
         },
        {
            'name': 'INS',
            'description': 'Instance Administrator. Has jurisdiction for a instance in an organisation\'s structure'
        },
        {
            'name': 'ENT',
            'description': 'Entity Administrator. Has jurisdiction for a entity in an organisation\'s structure'
        },
        {
            'name': 'UNI',
            'description': 'Unit Administrator. Has jurisdiction for a unit in an organisation\'s structure'
        },
    ]

    for type in default_task_types:
        admin_type.objects.get_or_create(**type)
  


class Migration(migrations.Migration):

    dependencies = [
        ('core',  '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin_types),
        migrations.RunPython(create_default_entity_types),
        migrations.RunPython(create_default_unit_types),
    ]
