# Generated by Django 5.1 on 2025-04-29 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationChart',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orgChartID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('orgChartName', models.CharField(max_length=256)),
                ('orgDataID', models.IntegerField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('Lapsed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('Suspended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('LastUpdatedByID', models.ForeignKey(db_column='LastUpdatedByID', on_delete=django.db.models.deletion.CASCADE, related_name='updated_org_charts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('entityID', models.ForeignKey(db_column='entityID', on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Chart',
                'verbose_name_plural': 'Organization Charts',
                'db_table': 'tija_org_charts',
                'ordering': ['-DateAdded'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationChartPositionAssignment',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positionAssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('orgDataID', models.IntegerField()),
                ('positionID', models.IntegerField()),
                ('positionTypeID', models.IntegerField(blank=True, null=True)),
                ('positionTitle', models.CharField(max_length=255)),
                ('positionDescription', models.TextField(blank=True, null=True)),
                ('positionParentID', models.IntegerField()),
                ('positionOrder', models.IntegerField(blank=True, null=True)),
                ('positionLevel', models.CharField(blank=True, max_length=120, null=True)),
                ('positionCode', models.CharField(blank=True, max_length=120, null=True)),
                ('Lapsed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('Suspended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('LastUpdatedByID', models.ForeignKey(db_column='LastUpdatedByID', on_delete=django.db.models.deletion.CASCADE, related_name='updated_position_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('entityID', models.ForeignKey(db_column='entityID', on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='core.entity')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('orgChartID', models.ForeignKey(db_column='orgChartID', on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='core.organisationchart')),
            ],
            options={
                'verbose_name': 'Position Assignment',
                'verbose_name_plural': 'Position Assignments',
                'db_table': 'tija_org_chart_position_assignments',
                'ordering': ['positionOrder', 'positionLevel', 'positionTitle'],
            },
        ),
    ]
