# Generated by Django 5.1 on 2024-08-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('BR', 'Branch'), ('DEP', 'Department'), ('SEC', 'Section'), ('TEA', 'Team')], default='DEP', max_length=3),
        ),
        migrations.AlterField(
            model_name='admintype',
            name='name',
            field=models.CharField(choices=[('SUP', 'SuperUser'), ('INS', 'Instance Admin'), ('ENT', 'Entity Admin'), ('UNI', 'Unit Admin')], max_length=15),
        ),
    ]
