# Generated by Django 5.1 on 2025-04-23 06:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_default_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='description',
            new_name='entityDescription',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='instance',
            new_name='instanceID',
        ),
        migrations.RenameField(
            model_name='entitytype',
            old_name='description',
            new_name='entityTypeDescription',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='parent_entity',
        ),
        migrations.RemoveField(
            model_name='entitytype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entitytype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='code',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='name',
        ),
        migrations.AddField(
            model_name='entity',
            name='DateAdded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 23, 6, 36, 7, 797202, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='Lapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='LastUpdateByID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='Suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityCountry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='entityName',
            field=models.CharField(default='def', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='entityPIN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityParentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entities', to='core.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityPhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entityTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.entitytype'),
        ),
        migrations.AddField(
            model_name='entity',
            name='registrationNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='DateAdded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 23, 6, 40, 51, 244868, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entitytype',
            name='Lapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='LastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='Suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='entityTypeID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entitytype',
            name='entityTypeTitle',
            field=models.CharField(default='def', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='DateAdded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 23, 6, 41, 39, 492258, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='Lapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instance',
            name='Suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instance',
            name='instanceID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='instanceName',
            field=models.CharField(default='def', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('industrySectorID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('industryTitle', models.CharField(max_length=255)),
                ('industryCategory', models.CharField(max_length=255)),
                ('Suspended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('LastUpdatedByID', models.ForeignKey(db_column='LastUpdatedByID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='industrySectorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.industrysector'),
        ),
        migrations.AddField(
            model_name='instance',
            name='industrySector',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.industrysector'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrganisationData',
            fields=[
                ('orgDataID', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('orgLogo', models.CharField(max_length=255)),
                ('orgName', models.CharField(max_length=255)),
                ('numberOfEmployees', models.IntegerField()),
                ('registrationNumber', models.CharField(max_length=255)),
                ('orgPIN', models.CharField(max_length=255)),
                ('costCenterEnabled', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], max_length=10)),
                ('orgAddress', models.CharField(max_length=255)),
                ('orgPostalCode', models.CharField(max_length=20)),
                ('orgCity', models.CharField(max_length=100)),
                ('orgCountry', models.CharField(max_length=100)),
                ('orgPhoneNumber1', models.CharField(max_length=20)),
                ('orgPhoneNumber2', models.CharField(blank=True, max_length=20, null=True)),
                ('orgEmail', models.EmailField(max_length=254)),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('Lapsed', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('Suspended', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('LastUpdatedByID', models.ForeignKey(db_column='LastUpdatedByID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industrySectorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.industrysector')),
                ('instanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instance')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='orgDataID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.organisationdata'),
        ),
    ]
