# Generated by Django 4.2.20 on 2025-05-05 11:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_created_at_user_last_updated_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='industrysector',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
