# Generated by Django 4.2.21 on 2025-05-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_created_by'),  # Replace with your last migration name
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationchartpositionassignment',
            name='orgDataID',
        ),
    ]
