# Generated by Django 4.2.21 on 2025-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_orgdataid_from_position_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationchartpositionassignment',
            name='positionParentID',
            field=models.ForeignKey(
                blank=True, 
                db_column='positionParentID', 
                null=True, 
                on_delete=models.SET_NULL,
                related_name='subordinates', 
                to='core.organisationchartpositionassignment'
            ),
        ),
    ]
