# Generated by Django 4.2.21 on 2025-05-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_make_position_parent_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL to execute
            "ALTER TABLE tija_org_chart_position_assignments ALTER COLUMN \"entityID\" DROP NOT NULL;",
            # SQL to rollback if needed
            "ALTER TABLE tija_org_chart_position_assignments ALTER COLUMN \"entityID\" SET NOT NULL;"
        ),
    ]
