# Generated by Django 5.2.1 on 2025-05-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_make_entityid_nullable'),
    ]

    operations = [
     
        migrations.RemoveField(
            model_name='organisationchartpositionassignment',
            name='positionTypeID',
        ),
        migrations.AlterField(
            model_name='organisationchart',
            name='orgDataID',
            field=models.OneToOneField(db_column='orgDataID', on_delete=django.db.models.deletion.CASCADE, related_name='organisation_chart', to='core.organisationdata'),
        ),
    ]
