# Generated by Django 5.2.1 on 2025-05-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_organisationchartpositionassignment_entityid_and_more'),
    ]

    operations = [
    # Commented out because the column does not exist
     # migrations.RemoveField(
     #    model_name='organisationchartpositionassignment',
     #     name='entityID',
     # ),
    ]
