# Generated by Django 5.2.1 on 2025-05-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_organisationchartpositionassignment_entityid'),
    ]

    operations = [
      #  migrations.RemoveField(
       #     model_name='organisationchartpositionassignment',
       #     name='entityID',
       # ),
    ]
