# Generated by Django 5.2.1 on 2025-05-26 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_organisationchartpositionassignment_entityid'),
    ]

    operations = [
       # migrations.RemoveField(
       #     model_name='organisationchartpositionassignment',
      #      name='entityID',
      #  ),
        migrations.CreateModel(
            name='OrganisationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ORGADMIN', 'Organisation Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('VIEWER', 'Viewer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.organisationdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organisation', 'role')},
            },
        ),
    ]
