# Generated by Django 5.2.1 on 2025-05-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_organisationchartpositionassignment_entityid_and_more'),
    ]

    operations = [
       # migrations.RemoveField(
       #     model_name='organisationchartpositionassignment',
      #      name='entityID',
      #  ),
        migrations.AddField(
            model_name='organisationdata',
            name='orgDocument',
            field=models.FileField(blank=True, null=True, upload_to='organisation_documents/'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='core.organisationdata')),
            ],
        ),
    ]
