# Generated by Django 5.1.5 on 2025-06-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_admin_entity_admin_instance_admin_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionprofile',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_profiles', to='core.organisationdata'),
        ),
        migrations.AlterField(
            model_name='permissionprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='permissionprofile',
            unique_together={('organisation', 'name')},
        ),
    ]
