# Generated by Django 5.2.3 on 2025-07-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_permissionprofile_organisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='instance',
            new_name='jurisdiction_instance',
        ),
    ]
