# Generated by Django 5.2.3 on 2025-07-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_instance_admin_jurisdiction_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='jurisdiction_instance',
            new_name='instance',
        ),
    ]
