# Generated by Django 5.1.1 on 2024-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
    ]


# Generated by Django 5.1.1 on 2024-11-13 07:11

from django.db import migrations


# Generated by Django 5.1.1 on 2024-11-13 06:42

from django.db import migrations


def create_default_sales_statuses(apps, schema_editor):
    sales_status = apps.get_model('hub', 'SalesStatus')

    default_statuses = [
        {'name': 'CLOSED_ACCEPTED', },
        {'name': 'PROPOSAL'},
        {'name': 'CLOSED_REJECTED'},
        {'name': "OPPORTUNITY"},
        {'name': 'LEAD'},
    ]

    for status in default_statuses:
        sales_status.objects.get_or_create(**status)

def create_default_task_statuses(apps, schema_editor):
    task_status = apps.get_model('hub', 'TaskStatus')
    sales_task_status = apps.get_model('hub', 'SalesTaskStatus')

    default_statuses = [
        {'name': 'COMPLETED'},
        {'name': 'IN PROGRESS'},
        {'name': 'PENDING'},
    ]

    for status in default_statuses:
        task_status.objects.get_or_create(**status)


def create_default_task_types(apps,schema_editor):
    task_types = apps.get_model('hub','TaskType')
    default_task_types = [
        {'name': 'Consulting'},
        {'name': 'Internal Work'},
        {
            'name': 'Project Task'
        },
    ]

    for type in default_task_types:
        task_types.objects.get_or_create(**type)
  

def create_default_leave_types(apps,schema_editor):
    leave_types = apps.get_model('hub','LeaveType')
    default_leave_types = [
        {
            'name': 'Parental Leave',
            'is_paid' : 'True'
        },
        {
            'name': 'Normal Leave',
            'is_paid': 'True'
        },
        {
            'name': 'Unpaid Leave',
            'is_paid': 'False'
        },
    ]

    for type in default_leave_types:
        leave_types.objects.get_or_create(**type)
  

class Migration(migrations.Migration):

    dependencies = [
        ('hub',  '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_sales_statuses),
        migrations.RunPython(create_default_task_types),
        migrations.RunPython(create_default_task_statuses),
        migrations.RunPython(create_default_leave_types),
    ]
