# Generated by Django 5.1.5 on 2025-06-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_permissionprofile_organisation_and_more'),
        ('hub', '0002_contact_user_customer_instance_customer_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instance'),
        ),
    ]
