# Generated by Django 5.1.3 on 2025-02-13 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_add_default_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workentries',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workentries',
            name='start_time',
        ),
        migrations.AddField(
            model_name='workentries',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='work_entries/'),
        ),
        migrations.AlterField(
            model_name='workentries',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
