# Generated by Django 5.1.1 on 2024-11-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_add_default_data'),
    ]

    operations = [
        # Commented out to prevent duplicate columns from being added
        # migrations.AddField(
        #     model_name='workentries',
        #     name='sale',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.sales'),
        # ),
        # migrations.AddField(
        #     model_name='workentries',
        #     name='sales_task',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.salestask'),
        # ),
    ]
