# Generated by Django 5.1.3 on 2025-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_workentries_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='absences/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
    ]
