# Generated by Django 5.2.3 on 2025-07-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_jurisdiction_instance_admin_instance'),
        ('hub', '0004_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instance'),
        ),
    ]
